string=input("Enter String: ")
swapped_string=string.swapcase()
uppercase_string=string.upper()
lowercase_string=string.lower()
capitalised_string=string.capitalize()
print("Uppercase:",uppercase_string)
print(lowercase_string)
print(capitalised_string)
print( swapped_string)
